import sys
import os
from rich.console import Console
from rich.panel import Panel
from rich.live import Live
from rich.markdown import Markdown
from rich.align import Align
from llama_cpp import Llama

# --- AESTHETICS ---
console = Console()
STYLE_BORDER = "cyan"
STYLE_PROMPT = "bold yellow"

def load_model(model_path):
    """Load TinyLlama."""
    if not os.path.exists(model_path):
        console.print(f"[bold red]Error:[/] Could not find '{model_path}'")
        sys.exit(1)

    with console.status("[bold magenta]Summoning the Triad...[/]", spinner="dots"):
        # n_ctx=2048 is plenty for poetry
        return Llama(model_path=model_path, n_ctx=2048, verbose=False)

def generate_triad_poem(llm, w1, w2, w3):
    """Prompt TinyLlama to use exactly three words."""
    
    system_prompt = (
        "You are a creative poet. "
        "Write a short, atmospheric poem that includes the user's three words. "
        "Do not explain the poem."
    )
    
    user_prompt = f"Write a poem using these three words: '{w1}', '{w2}', and '{w3}'."

    # TinyLlama Format
    full_prompt = (
        f"<|system|>\n{system_prompt}</s>\n"
        f"<|user|>\n{user_prompt}</s>\n"
        f"<|assistant|>\n"
    )

    return llm(
        full_prompt, 
        max_tokens=256, 
        stop=["</s>", "<|user|>"], 
        stream=True, 
        temperature=0.8
    )

def main():
    console.clear()
    console.rule("[bold magenta] PoetBot[/]")
    console.print(Align.center("[italic dim]Give me three seeds, I will grow a forest.[/]"))
    console.print("\n")

    # Ensure this matches your downloaded file name!
    MODEL_PATH = "tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf" 
    llm = load_model(MODEL_PATH)
    
    console.print(Panel("Ready for input...", style=STYLE_BORDER, expand=False))

    while True:
        console.print(f"\n[{STYLE_PROMPT}]Enter 3 words (separated by spaces):[/{STYLE_PROMPT}] ", end="")
        user_input = input().strip()
        
        if user_input.lower() in ['q', 'quit', 'exit']:
            console.print("\n[magenta]Disconnected.[/]")
            break

        # Logic to split the input into 3 words
        words = user_input.split()
        
        # Validation: Ensure exactly 3 words are entered
        if len(words) != 3:
            console.print("[red]Please enter exactly three words (e.g. 'moon glass whisper').[/]")
            continue

        w1, w2, w3 = words

        console.print("\n")
        
        # Live generation display
        poem_content = ""
        panel_title = f"[bold magenta]{w1.upper()}  •  {w2.upper()}  •  {w3.upper()}[/]"
        
        # We start with an empty panel
        with Live(Panel("", title="[italic]Weaving...[/]", border_style=STYLE_BORDER), refresh_per_second=10, console=console) as live:
            stream = generate_triad_poem(llm, w1, w2, w3)
            
            for output in stream:
                token = output['choices'][0]['text']
                poem_content += token
                
                live.update(Panel(
                    Markdown(poem_content, justify="center"), 
                    title=panel_title,
                    border_style=STYLE_BORDER,
                    padding=(1, 2)
                ))

        console.print(Align.right("[dim]-- generated by TinyLlama --[/]"))
        console.print("\n")

if __name__ == "__main__":
    main()